max_retry_times = 1


[api_keys]
[[api_keys.gpt-4o]]
api_key = "sk-1234"
base_url = "https://example.com/v1/"
model = "gpt-4o"

# E.g.
# [[api_keys.{your model_alias}]] # it dosen't have to be the same as *model name*.
# api_key = [your api_key]
# base_url = [your base_url]
# model = "{model_name for api call}" # the model name should compatible with the API.
# see example for alias:
# [[api_keys.openai-3.5]]
# api_key = sk-xx
# model = "gpt-3.5-turbo"


# To run active agent directly, fill the following fields.
# For active agent part, we set the model as activeagent, so just fill directly.
[[api_keys.activeagent]]
api_key = "sk-"
model = "gpt-4o"

[request]
default_completions_model = "gpt-4o" #which model will be used in experiment if not set in code.
save_completions = true # Whether to store the completions in the repo, if true, the completions will be stored in `.completions/`
use_cache = false # Whether to use cache, if true, when given exact same input stored in `.completions`, the cache will be activated and return the response stored .

# !If change `default_completions_model`, make sure you use *alias* instead of *model name*. i.e. use `openi-3.5` rather than `gpt-3.5-turbo`.

[multimodal.image]
default_model = "gpt-4o" # use model alias.
